In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('shopping_trends.csv')

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
df.dtypes

Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [8]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.dtypes

Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [10]:
df[['Subscription Status','Preferred Payment Method','Gender']]

     Subscription Status Preferred Payment Method  Gender
0                    Yes                    Venmo    Male
1                    Yes                     Cash    Male
2                    Yes              Credit Card    Male
3                    Yes                   PayPal    Male
4                    Yes                   PayPal    Male
...                  ...                      ...     ...
3895                  No                    Venmo  Female
3896                  No            Bank Transfer  Female
3897                  No                    Venmo  Female
3898                  No                    Venmo  Female
3899                  No                    Venmo  Female

[3900 rows x 3 columns]

In [12]:
type(df.dtypes)

pandas.core.series.Series

In [13]:
df.dtypes=='object'

Customer ID                 False
Age                         False
Gender                       True
Item Purchased               True
Category                     True
Purchase Amount (USD)       False
Location                     True
Size                         True
Color                        True
Season                       True
Review Rating               False
Subscription Status          True
Payment Method               True
Shipping Type                True
Discount Applied             True
Promo Code Used              True
Previous Purchases          False
Preferred Payment Method     True
Frequency of Purchases       True
dtype: bool

In [15]:
df.dtypes[df.dtypes=='object'].index

Index(['Gender', 'Item Purchased', 'Category', 'Location', 'Size', 'Color',
       'Season', 'Subscription Status', 'Payment Method', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Preferred Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [16]:
df[df.dtypes[df.dtypes=='object'].index]

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Preferred Payment Method,Frequency of Purchases
0,Male,Blouse,Clothing,Kentucky,L,Gray,Winter,Yes,Credit Card,Express,Yes,Yes,Venmo,Fortnightly
1,Male,Sweater,Clothing,Maine,L,Maroon,Winter,Yes,Bank Transfer,Express,Yes,Yes,Cash,Fortnightly
2,Male,Jeans,Clothing,Massachusetts,S,Maroon,Spring,Yes,Cash,Free Shipping,Yes,Yes,Credit Card,Weekly
3,Male,Sandals,Footwear,Rhode Island,M,Maroon,Spring,Yes,PayPal,Next Day Air,Yes,Yes,PayPal,Weekly
4,Male,Blouse,Clothing,Oregon,M,Turquoise,Spring,Yes,Cash,Free Shipping,Yes,Yes,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,Female,Hoodie,Clothing,Virginia,L,Turquoise,Summer,No,Cash,2-Day Shipping,No,No,Venmo,Weekly
3896,Female,Backpack,Accessories,Iowa,L,White,Spring,No,PayPal,Store Pickup,No,No,Bank Transfer,Bi-Weekly
3897,Female,Belt,Accessories,New Jersey,L,Green,Spring,No,Credit Card,Standard,No,No,Venmo,Quarterly
3898,Female,Shoes,Footwear,Minnesota,S,Brown,Summer,No,PayPal,Express,No,No,Venmo,Weekly
3899,Female,Handbag,Accessories,California,M,Beige,Spring,No,Bank Transfer,Store Pickup,No,No,Venmo,Quarterly

In [17]:
df[df.dtypes[df.dtypes=='object'].index].describe()

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Preferred Payment Method,Frequency of Purchases
count,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900
unique,2,25,4,50,4,25,4,2,6,6,2,2,6,7
top,Male,Blouse,Clothing,Montana,M,Olive,Spring,No,Credit Card,Free Shipping,No,No,PayPal,Every 3 Months
freq,2652,171,1737,96,1755,177,999,2847,696,675,2223,2223,677,584

In [18]:
df[df.dtypes[df.dtypes=='int64'].index].describe()

       Customer ID          Age  Purchase Amount (USD)  Previous Purchases
count  3900.000000  3900.000000            3900.000000         3900.000000
mean   1950.500000    44.068462              59.764359           25.351538
std    1125.977353    15.207589              23.685392           14.447125
min       1.000000    18.000000              20.000000            1.000000
25%     975.750000    31.000000              39.000000           13.000000
50%    1950.500000    44.000000              60.000000           25.000000
75%    2925.250000    57.000000              81.000000           38.000000
max    3900.000000    70.000000             100.000000           50.000000

In [19]:
df[df.dtypes[df.dtypes=='float64'].index].describe()

       Review Rating
count    3900.000000
mean        3.749949
std         0.716223
min         2.500000
25%         3.100000
50%         3.700000
75%         4.400000
max         5.000000

In [20]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Payment Method',
       'Shipping Type', 'Discount Applied', 'Promo Code Used',
       'Previous Purchases', 'Preferred Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [22]:
df[['Customer ID', 'Age']][4:11]

    Customer ID  Age
4             5   45
5             6   46
6             7   63
7             8   27
8             9   26
9            10   57
10           11   53

In [23]:
df['new']=0

In [24]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly,0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly,0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly,0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0

In [25]:
df['new1']=df['Customer ID']+df['Age']

In [26]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,0,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,...,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly,0,3936
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,...,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,0,3949
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,...,No,Credit Card,Standard,No,No,24,Venmo,Quarterly,0,3944
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,No,PayPal,Express,No,No,24,Venmo,Weekly,0,3943
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,...,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0,3952

In [27]:
pd.Categorical(df['Shipping Type'])

['Express', 'Express', 'Free Shipping', 'Next Day Air', 'Free Shipping', ..., '2-Day Shipping', 'Store Pickup', 'Standard', 'Express', 'Store Pickup']
Length: 3900
Categories (6, object): ['2-Day Shipping', 'Express', 'Free Shipping', 'Next Day Air', 'Standard', 'Store Pickup']

In [28]:
pd.Categorical(df['Promo Code Used'])

['Yes', 'Yes', 'Yes', 'Yes', 'Yes', ..., 'No', 'No', 'No', 'No', 'No']
Length: 3900
Categories (2, object): ['No', 'Yes']

In [29]:
pd.Categorical(df['Preferred Payment Method'])

['Venmo', 'Cash', 'Credit Card', 'PayPal', 'PayPal', ..., 'Venmo', 'Bank Transfer', 'Venmo', 'Venmo', 'Venmo']
Length: 3900
Categories (6, object): ['Bank Transfer', 'Cash', 'Credit Card', 'Debit Card', 'PayPal', 'Venmo']

In [32]:
pd.Categorical(df['Frequency of Purchases']).unique()

['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly', 'Monthly', 'Every 3 Months']
Categories (7, object): ['Annually', 'Bi-Weekly', 'Every 3 Months', 'Fortnightly', 'Monthly', 'Quarterly', 'Weekly']

In [34]:
df[df['Age']>25]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,0,50
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,...,Yes,Venmo,Standard,Yes,Yes,14,Venmo,Weekly,0,52
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly,0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,...,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly,0,3936
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,...,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,0,3949
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,...,No,Credit Card,Standard,No,No,24,Venmo,Quarterly,0,3944
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,No,PayPal,Express,No,No,24,Venmo,Weekly,0,3943
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,...,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0,3952

In [35]:
len(df)-len(df[df['Age']>25])

571

In [36]:
#25.35153

In [37]:
df[df['Purchase Amount (USD)']<59.764359]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,0,50
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,...,Yes,Venmo,Standard,Yes,Yes,14,Venmo,Weekly,0,52
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,...,Yes,Debit Card,Free Shipping,Yes,Yes,19,Credit Card,Weekly,0,35
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,...,Yes,PayPal,2-Day Shipping,Yes,Yes,4,Cash,Quarterly,0,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3887,3888,40,Female,Shirt,Clothing,34,Kansas,M,Charcoal,Spring,...,No,PayPal,Express,No,No,1,Credit Card,Quarterly,0,3928
3891,3892,36,Female,Dress,Clothing,30,Colorado,L,Peach,Winter,...,No,Cash,Free Shipping,No,No,6,Bank Transfer,Quarterly,0,3928
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,...,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly,0,3936
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,...,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,0,3949
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,...,No,Credit Card,Standard,No,No,24,Venmo,Quarterly,0,3944

In [38]:
df[df['Purchase Amount (USD)']>59.764359]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly,0,70
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,...,Yes,Venmo,Express,Yes,Yes,8,Venmo,Annually,0,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3892,3893,35,Female,Jewelry,Accessories,86,Michigan,L,Indigo,Summer,...,No,Bank Transfer,Standard,No,No,5,PayPal,Fortnightly,0,3928
3893,3894,21,Female,Hat,Accessories,64,Massachusetts,L,White,Fall,...,No,Bank Transfer,Store Pickup,No,No,29,Bank Transfer,Bi-Weekly,0,3915
3894,3895,66,Female,Skirt,Clothing,78,Connecticut,L,White,Spring,...,No,Cash,2-Day Shipping,No,No,44,Credit Card,Every 3 Months,0,3961
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,No,PayPal,Express,No,No,24,Venmo,Weekly,0,3943
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,...,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0,3952

In [43]:
df[df['Purchase Amount (USD)']==55]['Customer ID']

48        49
153      154
206      207
406      407
416      417
665      666
799      800
965      966
966      967
1159    1160
1171    1172
1193    1194
1228    1229
1382    1383
1501    1502
1539    1540
1549    1550
1756    1757
1856    1857
2033    2034
2165    2166
2320    2321
2325    2326
2408    2409
2485    2486
2616    2617
2867    2868
2890    2891
2988    2989
3013    3014
3074    3075
3154    3155
3271    3272
3399    3400
3446    3447
3544    3545
3554    3555
3588    3589
3699    3700
3706    3707
3803    3804
Name: Customer ID, dtype: int64

In [44]:
df[df['Gender']=='Male']

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,0,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2647,2648,60,Male,Shoes,Footwear,58,South Carolina,M,Red,Summer,...,No,Debit Card,2-Day Shipping,No,No,25,Debit Card,Annually,0,2708
2648,2649,51,Male,Pants,Clothing,84,Illinois,M,Gray,Spring,...,No,Venmo,Next Day Air,No,No,14,PayPal,Bi-Weekly,0,2700
2649,2650,23,Male,Gloves,Accessories,21,Minnesota,M,Magenta,Fall,...,No,Credit Card,Store Pickup,No,No,14,Bank Transfer,Fortnightly,0,2673
2650,2651,20,Male,Socks,Clothing,35,Oregon,L,Maroon,Summer,...,No,PayPal,Standard,No,No,46,Credit Card,Every 3 Months,0,2671
2651,2652,51,Male,Sneakers,Footwear,43,Tennessee,M,Cyan,Summer,...,No,Venmo,Store Pickup,No,No,27,PayPal,Quarterly,0,2703

In [45]:
df[df['Gender']=='Female']

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
2652,2653,23,Female,Shorts,Clothing,20,Maryland,L,Cyan,Summer,...,No,Debit Card,2-Day Shipping,No,No,46,Credit Card,Monthly,0,2676
2653,2654,67,Female,Blouse,Clothing,36,Wisconsin,L,Lavender,Fall,...,No,Credit Card,Express,No,No,24,Venmo,Every 3 Months,0,2721
2654,2655,23,Female,Coat,Outerwear,70,Idaho,S,Pink,Fall,...,No,Debit Card,Next Day Air,No,No,4,PayPal,Annually,0,2678
2655,2656,26,Female,Sunglasses,Accessories,83,Wyoming,M,Gray,Summer,...,No,Credit Card,Standard,No,No,2,Credit Card,Fortnightly,0,2682
2656,2657,52,Female,Shorts,Clothing,76,Indiana,L,Yellow,Winter,...,No,Bank Transfer,Express,No,No,29,Bank Transfer,Fortnightly,0,2709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,...,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly,0,3936
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,...,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,0,3949
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,...,No,Credit Card,Standard,No,No,24,Venmo,Quarterly,0,3944
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,No,PayPal,Express,No,No,24,Venmo,Weekly,0,3943
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,...,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0,3952

In [47]:
df.head(4)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25

In [49]:
df['Gender']=='Female'

0       False
1       False
2       False
3       False
4       False
        ...
3895     True
3896     True
3897     True
3898     True
3899     True
Name: Gender, Length: 3900, dtype: bool

In [50]:
df['Purchase Amount (USD)']>73

0       False
1       False
2       False
3        True
4       False
        ...
3895    False
3896    False
3897    False
3898     True
3899     True
Name: Purchase Amount (USD), Length: 3900, dtype: bool

In [52]:
df[(df['Gender']=='Female') & (df['Purchase Amount (USD)']>73 )]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
2655,2656,26,Female,Sunglasses,Accessories,83,Wyoming,M,Gray,Summer,...,No,Credit Card,Standard,No,No,2,Credit Card,Fortnightly,0,2682
2656,2657,52,Female,Shorts,Clothing,76,Indiana,L,Yellow,Winter,...,No,Bank Transfer,Express,No,No,29,Bank Transfer,Fortnightly,0,2709
2657,2658,52,Female,Dress,Clothing,81,Texas,M,Pink,Summer,...,No,PayPal,Express,No,No,7,Credit Card,Fortnightly,0,2710
2660,2661,24,Female,Pants,Clothing,85,South Carolina,L,Yellow,Spring,...,No,Debit Card,Express,No,No,44,Venmo,Annually,0,2685
2661,2662,43,Female,Boots,Footwear,96,Michigan,XL,Olive,Fall,...,No,Debit Card,Express,No,No,20,Bank Transfer,Annually,0,2705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3890,3891,35,Female,Shirt,Clothing,81,Nebraska,XL,Green,Winter,...,No,Credit Card,Standard,No,No,33,Debit Card,Annually,0,3926
3892,3893,35,Female,Jewelry,Accessories,86,Michigan,L,Indigo,Summer,...,No,Bank Transfer,Standard,No,No,5,PayPal,Fortnightly,0,3928
3894,3895,66,Female,Skirt,Clothing,78,Connecticut,L,White,Spring,...,No,Cash,2-Day Shipping,No,No,44,Credit Card,Every 3 Months,0,3961
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,No,PayPal,Express,No,No,24,Venmo,Weekly,0,3943
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,...,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0,3952

In [53]:
df[(df['Gender']=='Male') & (df['Purchase Amount (USD)']>73 )]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly,0,70
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,...,Yes,Venmo,Express,Yes,Yes,8,Venmo,Annually,0,35
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,...,Yes,Credit Card,Store Pickup,Yes,Yes,8,PayPal,Monthly,0,80
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,...,Yes,Venmo,Standard,Yes,Yes,46,Debit Card,Bi-Weekly,0,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2640,2641,30,Male,Skirt,Clothing,75,Indiana,L,Olive,Summer,...,No,Debit Card,Store Pickup,No,No,45,Venmo,Bi-Weekly,0,2671
2642,2643,39,Male,Belt,Accessories,87,Iowa,L,Peach,Summer,...,No,Debit Card,Store Pickup,No,No,48,Bank Transfer,Annually,0,2682
2644,2645,25,Male,Pants,Clothing,83,New Mexico,M,Turquoise,Spring,...,No,PayPal,Standard,No,No,4,Bank Transfer,Every 3 Months,0,2670
2645,2646,23,Male,Scarf,Accessories,81,Louisiana,L,Olive,Spring,...,No,Bank Transfer,Store Pickup,No,No,24,Bank Transfer,Bi-Weekly,0,2669
2648,2649,51,Male,Pants,Clothing,84,Illinois,M,Gray,Spring,...,No,Venmo,Next Day Air,No,No,14,PayPal,Bi-Weekly,0,2700

In [54]:
df[(df['Gender']=='Female') | (df['Purchase Amount (USD)']>73 )]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly,0,70
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,...,Yes,Venmo,Express,Yes,Yes,8,Venmo,Annually,0,35
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,...,Yes,Credit Card,Store Pickup,Yes,Yes,8,PayPal,Monthly,0,80
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,...,Yes,Venmo,Standard,Yes,Yes,46,Debit Card,Bi-Weekly,0,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,...,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly,0,3936
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,...,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,0,3949
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,...,No,Credit Card,Standard,No,No,24,Venmo,Quarterly,0,3944
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,No,PayPal,Express,No,No,24,Venmo,Weekly,0,3943
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,...,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly,0,3952

In [55]:
df.head(4)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,0,25

In [56]:
max(df['Purchase Amount (USD)'])

100

In [57]:
df[df['Purchase Amount (USD)']==max(df['Purchase Amount (USD)'])]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
42,43,20,Male,Coat,Outerwear,100,Tennessee,M,Beige,Spring,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,15,PayPal,Annually,0,63
95,96,37,Male,Sneakers,Footwear,100,Missouri,L,Pink,Fall,...,Yes,PayPal,Free Shipping,Yes,Yes,48,PayPal,Monthly,0,133
193,194,36,Male,Belt,Accessories,100,North Dakota,S,Silver,Fall,...,Yes,PayPal,Standard,Yes,Yes,29,Venmo,Annually,0,230
204,205,24,Male,Sneakers,Footwear,100,Arizona,M,Yellow,Fall,...,Yes,PayPal,Store Pickup,Yes,Yes,35,Cash,Bi-Weekly,0,229
243,244,25,Male,Jewelry,Accessories,100,Kentucky,M,Olive,Winter,...,Yes,Credit Card,2-Day Shipping,Yes,Yes,4,Debit Card,Monthly,0,269
248,249,47,Male,Belt,Accessories,100,Pennsylvania,M,Blue,Winter,...,Yes,Venmo,Express,Yes,Yes,33,PayPal,Weekly,0,296
455,456,54,Male,Blouse,Clothing,100,Utah,XL,Gold,Fall,...,Yes,Credit Card,Store Pickup,Yes,Yes,50,Debit Card,Fortnightly,0,510
518,519,24,Male,Blouse,Clothing,100,Oregon,M,Beige,Fall,...,Yes,PayPal,Next Day Air,Yes,Yes,16,Venmo,Every 3 Months,0,543
581,582,32,Male,Sweater,Clothing,100,Iowa,XL,Charcoal,Winter,...,Yes,Credit Card,Store Pickup,Yes,Yes,12,Bank Transfer,Every 3 Months,0,614
615,616,67,Male,Sandals,Footwear,100,Maryland,L,Olive,Summer,...,Yes,Debit Card,Next Day Air,Yes,Yes,23,Venmo,Annually,0,683
769,770,52,Male,Socks,Clothing,100,Delaware,M,Silver,Spring,...,Yes,Credit Card,Store Pickup,Yes,Yes,8,PayPal,Monthly,0,822
861,862,46,Male,Skirt,Clothing,100,Virginia,XL,Green,Spring,...,Yes,PayPal,2-Day Shipping,Yes,Yes,35,Credit Card,Every 3 Months,0,908
1208,1209,20,Male,Boots,Footwear,100,Wisconsin,S,Red,Winter,...,No,Cash,2-Day Shipping,Yes,Yes,8,Debit Card,Annually,0,1229
1300,1301,67,Male,T-shirt,Clothing,100,West Virginia,M,Charcoal,Spring,...,No,Cash,Next Day Air,Yes,Yes,47,Credit Card,Every 3 Months,0,1368
1405,1406,33,Male,Socks,Clothing,100,New Hampshire,M,Peach,Winter,...,No,Cash,Store Pickup,Yes,Yes,39,Credit Card,Monthly,0,1439
1412,1413,25,Male,Shorts,Clothing,100,Michigan,M,Charcoal,Summer,...,No,Debit Card,2-Day Shipping,Yes,Yes,43,Venmo,Annually,0,1438
1421,1422,68,Male,Dress,Clothing,100,Pennsylvania,S,Gold,Spring,...,No,Credit Card,Standard,Yes,Yes,24,Bank Transfer,Fortnightly,0,1490
1456,1457,59,Male,Coat,Outerwear,100,Montana,S,Olive,Spring,...,No,Venmo,Store Pickup,Yes,Yes,30,PayPal,Every 3 Months,0,1516
1479,1480,48,Male,Coat,Outerwear,100,Washington,L,Black,Spring,...,No,Debit Card,Standard,Yes,Yes,2,Bank Transfer,Weekly,0,1528
1591,1592,18,Male,Skirt,Clothing,100,South Dakota,L,Gold,Winter,...,No,Bank Transfer,Next Day Air,Yes,Yes,24,PayPal,Annually,0,1610
1847,1848,46,Male,Sandals,Footwear,100,Arizona,XL,Cyan,Summer,...,No,Debit Card,Free Shipping,No,No,49,Credit Card,Weekly,0,1894
2071,2072,69,Male,Jacket,Outerwear,100,South Carolina,S,Yellow,Fall,...,No,Debit Card,Store Pickup,No,No,37,PayPal,Quarterly,0,2141
2214,2215,50,Male,Belt,Accessories,100,Idaho,L,Gold,Fall,...,No,Cash,Standard,No,No,20,Debit Card,Weekly,0,2265
2285,2286,34,Male,Belt,Accessories,100,Michigan,L,Pink,Summer,...,No,Cash,2-Day Shipping,No,No,38,PayPal,Every 3 Months,0,2320
2430,2431,20,Male,Jacket,Outerwear,100,North Dakota,XL,White,Summer,...,No,Cash,Express,No,No,42,Cash,Quarterly,0,2451
2802,2803,22,Female,Coat,Outerwear,100,Hawaii,L,Red,Fall,...,No,Bank Transfer,Store Pickup,No,No,42,Credit Card,Fortnightly,0,2825
2807,2808,56,Female,Hoodie,Clothing,100,Maryland,M,Charcoal,Spring,...,No,Debit Card,2-Day Shipping,No,No,10,Debit Card,Fortnightly,0,2864
2842,2843,28,Female,Coat,Outerwear,100,Arizona,L,Green,Fall,...,No,Cash,Standard,No,No,48,Debit Card,Quarterly,0,2871
2958,2959,55,Female,Skirt,Clothing,100,Ohio,M,Black,Summer,...,No,Venmo,Standard,No,No,28,PayPal,Monthly,0,3014
2971,2972,30,Female,Handbag,Accessories,100,Utah,L,Yellow,Fall,...,No,Credit Card,Next Day Air,No,No,9,PayPal,Every 3 Months,0,3002
2994,2995,69,Female,Sweater,Clothing,100,Nevada,S,White,Winter,...,No,Cash,Store Pickup,No,No,14,Bank Transfer,Quarterly,0,3064
3028,3029,62,Female,Dress,Clothing,100,California,L,Charcoal,Summer,...,No,PayPal,Free Shipping,No,No,7,PayPal,Every 3 Months,0,3091
3265,3266,40,Female,Sunglasses,Accessories,100,Alabama,M,White,Winter,...,No,Credit Card,Express,No,No,28,Credit Card,Fortnightly,0,3306
3321,3322,32,Female,Coat,Outerwear,100,Maine,S,Charcoal,Winter,...,No,Bank Transfer,Next Day Air,No,No,3,Venmo,Annually,0,3354
3725,3726,18,Female,Dress,Clothing,100,Oklahoma,S,Turquoise,Winter,...,No,Bank Transfer,Next Day Air,No,No,2,PayPal,Annually,0,3744
3837,3838,45,Female,Hoodie,Clothing,100,New Mexico,M,Green,Spring,...,No,Debit Card,Free Shipping,No,No,33,Bank Transfer,Fortnightly,0,3883

In [58]:
df[0:100:2]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,0,50
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly,0,70
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,...,Yes,Venmo,Express,Yes,Yes,8,Venmo,Annually,0,35
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,...,Yes,Credit Card,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly,0,64
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,...,Yes,PayPal,Express,Yes,Yes,37,Venmo,Fortnightly,0,74
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,...,Yes,PayPal,Free Shipping,Yes,Yes,34,Debit Card,Weekly,0,79
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,...,Yes,Venmo,Next Day Air,Yes,Yes,44,Debit Card,Bi-Weekly,0,42
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,17,Cash,Weekly,0,71
20,21,21,Male,Pants,Clothing,51,Louisiana,M,Black,Winter,...,Yes,Credit Card,Express,Yes,Yes,50,Cash,Every 3 Months,0,42
22,23,56,Male,Pants,Clothing,37,California,M,Peach,Summer,...,Yes,Cash,Store Pickup,Yes,Yes,32,Debit Card,Annually,0,79
24,25,18,Male,Jacket,Outerwear,22,Florida,M,Green,Fall,...,Yes,Cash,Store Pickup,Yes,Yes,16,Debit Card,Weekly,0,43
26,27,38,Male,Jewelry,Accessories,20,Nevada,M,Red,Spring,...,Yes,Cash,Next Day Air,Yes,Yes,13,Credit Card,Annually,0,65
28,29,54,Male,Handbag,Accessories,94,North Carolina,M,Gray,Fall,...,Yes,Debit Card,Free Shipping,Yes,Yes,41,PayPal,Every 3 Months,0,83
30,31,57,Male,Jewelry,Accessories,31,North Carolina,L,Black,Winter,...,Yes,Bank Transfer,Standard,Yes,Yes,16,Credit Card,Monthly,0,88
32,33,36,Male,Jacket,Outerwear,67,Kansas,M,Silver,Summer,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,37,Venmo,Annually,0,69
34,35,36,Male,T-shirt,Clothing,91,North Dakota,L,Violet,Spring,...,Yes,Debit Card,2-Day Shipping,Yes,Yes,38,PayPal,Quarterly,0,71
36,37,35,Male,T-shirt,Clothing,69,Illinois,M,Maroon,Winter,...,Yes,Cash,Free Shipping,Yes,Yes,44,PayPal,Fortnightly,0,72
38,39,29,Male,Dress,Clothing,37,Florida,M,Red,Winter,...,Yes,Debit Card,2-Day Shipping,Yes,Yes,44,Venmo,Every 3 Months,0,68
40,41,69,Male,Handbag,Accessories,76,Louisiana,L,Beige,Winter,...,Yes,PayPal,Next Day Air,Yes,Yes,31,Debit Card,Quarterly,0,110
42,43,20,Male,Coat,Outerwear,100,Tennessee,M,Beige,Spring,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,15,PayPal,Annually,0,63
44,45,39,Male,Hat,Accessories,53,Kentucky,S,Silver,Summer,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,45,PayPal,Weekly,0,84
46,47,57,Male,Shirt,Clothing,43,California,L,White,Summer,...,Yes,Venmo,Store Pickup,Yes,Yes,45,Cash,Quarterly,0,104
48,49,42,Male,Shirt,Clothing,55,Nevada,M,Orange,Summer,...,Yes,Debit Card,Store Pickup,Yes,Yes,38,Cash,Monthly,0,91
50,51,49,Male,Blouse,Clothing,28,Maryland,M,Red,Spring,...,Yes,Cash,Store Pickup,Yes,Yes,39,Debit Card,Bi-Weekly,0,100
52,53,42,Male,T-shirt,Clothing,20,Alaska,M,Green,Summer,...,Yes,Credit Card,Free Shipping,Yes,Yes,26,Credit Card,Weekly,0,95
54,55,47,Male,Coat,Outerwear,94,New Mexico,M,Brown,Summer,...,Yes,Bank Transfer,Next Day Air,Yes,Yes,35,Debit Card,Bi-Weekly,0,102
56,57,41,Male,Backpack,Accessories,73,Mississippi,XL,Brown,Summer,...,Yes,PayPal,Store Pickup,Yes,Yes,46,Credit Card,Weekly,0,98
58,59,69,Male,Hoodie,Clothing,54,Missouri,M,Charcoal,Summer,...,Yes,Credit Card,Free Shipping,Yes,Yes,29,Venmo,Monthly,0,128
60,61,50,Male,Sweater,Clothing,37,Idaho,L,Brown,Summer,...,Yes,Credit Card,Express,Yes,Yes,17,Cash,Weekly,0,111
62,63,30,Male,Sneakers,Footwear,21,Mississippi,S,Magenta,Spring,...,Yes,Credit Card,Free Shipping,Yes,Yes,31,Credit Card,Fortnightly,0,93
64,65,65,Male,Boots,Footwear,83,Alabama,S,Green,Fall,...,Yes,PayPal,Standard,Yes,Yes,18,Debit Card,Fortnightly,0,130
66,67,31,Male,Blouse,Clothing,94,Pennsylvania,S,Magenta,Winter,...,Yes,Bank Transfer,2-Day Shipping,Yes,Yes,3,Venmo,Every 3 Months,0,98
68,69,57,Male,Handbag,Accessories,46,Utah,L,Silver,Summer,...,Yes,Credit Card,Next Day Air,Yes,Yes,21,Cash,Every 3 Months,0,126
70,71,22,Male,Belt,Accessories,29,Alabama,M,Magenta,Fall,...,Yes,Credit Card,Express,Yes,Yes,32,Debit Card,Every 3 Months,0,93
72,73,18,Male,Dress,Clothing,26,Georgia,M,Olive,Winter,...,Yes,Debit Card,Store Pickup,Yes,Yes,21,Bank Transfer,Every 3 Months,0,91
74,75,49,Male,Gloves,Accessories,58,Indiana,L,Violet,Spring,...,Yes,PayPal,Express,Yes,Yes,3,Cash,Monthly,0,124
76,77,50,Male,Hat,Accessories,43,Delaware,S,Teal,Summer,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,32,Venmo,Monthly,0,127
78,79,50,Male,Skirt,Clothing,91,Nebraska,M,Maroon,Spring,...,Yes,Venmo,Free Shipping,Yes,Yes,50,Venmo,Fortnightly,0,129
80,81,19,Male,Sandals,Footwear,72,New York,XL,Blue,Summer,...,Yes,Credit Card,Store Pickup,Yes,Yes,24,Credit Card,Every 3 Months,0,100
82,83,19,Male,Pants,Clothing,28,Georgia,S,Olive,Spring,...,Yes,Bank Transfer,2-Day Shipping,Yes,Yes,21,Credit Card,Every 3 Months,0,102
84,85,52,Male,Coat,Outerwear,32,Arizona,S,Peach,Spring,...,Yes,Cash,Standard,Yes,Yes,42,Bank Transfer,Every 3 Months,0,137
86,87,24,Male,Hoodie,Clothing,41,Nevada,L,Pink,Spring,...,Yes,Venmo,2-Day Shipping,Yes,Yes,47,Cash,Bi-Weekly,0,111
88,89,33,Male,T-shirt,Clothing,47,Wyoming,M,Orange,Fall,...,Yes,Credit Card,Free Shipping,Yes,Yes,35,Credit Card,Monthly,0,122
90,91,25,Male,Hat,Accessories,48,South Carolina,L,Violet,Summer,...,Yes,Venmo,Express,Yes,Yes,29,Credit Card,Monthly,0,116
92,93,61,Male,Jacket,Outerwear,87,Texas,M,Olive,Winter,...,Yes,Cash,2-Day Shipping,Yes,Yes,13,Venmo,Every 3 Months,0,154
94,95,58,Male,Skirt,Clothing,76,Nevada,S,Silver,Spring,...,Yes,Bank Transfer,Free Shipping,Yes,Yes,28,Credit Card,Weekly,0,153
96,97,32,Male,Gloves,Accessories,73,Delaware,S,Gold,Spring,...,Yes,Venmo,Express,Yes,Yes,43,Venmo,Every 3 Months,0,129
98,99,20,Male,Jeans,Clothing,67,New York,XL,Teal,Spring,...,Yes,Cash,Next Day Air,Yes,Yes,20,Bank Transfer,Annually,0,119

In [59]:
df.head(2)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21

In [60]:
df.iloc[0:2]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21

In [61]:
df.loc[0:2]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,new,new1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,0,56
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,0,21
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,0,53

In [65]:
df.iloc[0:2:,[0,1,2]]

   Customer ID  Age Gender
0            1   55   Male
1            2   19   Male

In [64]:
df.loc[0:2:,['Customer ID','Age','Gender']]

   Customer ID  Age Gender
0            1   55   Male
1            2   19   Male
2            3   50   Male